#ifndef CIHANLIBRARY_GLOBAL_H
#define CIHANLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CIHANLIBRARY_LIBRARY)
#  define CIHANLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CIHANLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CIHANLIBRARY_GLOBAL_H
