clear;clc;close all;
%% Read data
fid = fopen('featurevectors.csv', 'rt');
dataset = textscan(fid,'%f %f %f %f %s','Delimiter',',','CollectOutput',1);
fclose(fid);
%% Use PCA
[pcaTrainFeatures, pcaTrainClasses, pcaTestFeatures, pcaTestClasses] =...
    SortDataset(dataset{2}, dataset{1}, 0.6);
pcaVectors = UsePCA(pcaTrainFeatures, 2, '..\report\pcaTrans');
pcaTrainFeatures = pcaTrainFeatures * pcaVectors; 
pcaTestFeatures = pcaTestFeatures * pcaVectors;
%% Sort dataset
[...
    pcaConfusionMatrixTraining1, pcaConfusionMatrixTesting1,...
    pcaConfusionMatrixTraining2, pcaConfusionMatrixTesting2,...
    pcaConfusionMatrixTraining3, pcaConfusionMatrixTesting3,...
    pcaConfusionMatrixTraining4, pcaConfusionMatrixTesting4]...
    = Apply4Cases(pcaTrainFeatures, pcaTrainClasses, pcaTestFeatures,...
    pcaTestClasses, true, '..\report\pca');
%% Use LDA
[ldaTrainFeatures, ldaTrainClasses, ldaTestFeatures, ldaTestClasses] = ...
    SortDataset(dataset{2}, dataset{1}, 0.6);
ldaVectors = UseLDA(ldaTrainFeatures, ldaTrainClasses, 2, '..\report\ldaTrans');
ldaTrainFeatures = ldaTrainFeatures * ldaVectors; 
ldaTestFeatures = ldaTestFeatures * ldaVectors;
%% Sort dataset
[...
    ldaConfusionMatrixTraining1, ldaConfusionMatrixTesting1,...
    ldaConfusionMatrixTraining2, ldaConfusionMatrixTesting2,...
    ldaConfusionMatrixTraining3, ldaConfusionMatrixTesting3,...
    ldaConfusionMatrixTraining4, ldaConfusionMatrixTesting4]...
    = Apply4Cases(ldaTrainFeatures, ldaTrainClasses, ldaTestFeatures,...
    ldaTestClasses, true, '..\report\lda');